name: Compiler 🔨

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: NPM
        run: |
          npm install
      - name: Typescript Compiler
        run: |
          npm run compile
